### ISSUE TITLE
Kunsthalte Issues

### ISSUE THREAD

**Issue by 7alip** [wsvvrijheid/monorepo#243]
- [x] Backend: Add email notification for artists (approved, rejected)
- [x] Backend: Change art-editor email notifications

**Comment by MSKose** [comment]
Isn't the first issue resolved here https://github.com/wsvvrijheid/monorepo/pull/295 ? If not, which model is this referring to.

Also, is the second issue related to the lifecycle in apps/api/src/api/art/content-types/art/lifecycles.ts ? And in that case, is what's wanted just to alter the notification content in that lifecycle?

Thanks in advance.

**Comment by 7alip** [comment]
Hey @MSKose, that's right, you had already fix the first issue, thanks again.

Yes, in the second, we'd like to send an email to the editors whenever a new piece of art is created. However, we are still unsure whether we should send an email to all of the editors or to a single editor at random. For now, we can send emails to all of the editors.

Since we have not completed the roles for the users, I recommend using an env variable for the list of editor emails.

```ts
// EDITOR_EMAILS=editor1@example.com,editor2@example.com...
const editorEmails = process.env.EDITOR_EMAILS?.split(',')

if (editorEmails?.length > 0) {
  // send email to all at once
}
```
