### ISSUE TITLE
Blogs Table

### ISSUE THREAD

**Issue by MustafaTRKYLMZ** [wsvvrijheid/monorepo#259]
In admin project we want to show all blogs in a table. Use the same approach that we used for hashtags, posts etc.

**Comment by ertugrul-aydin** [comment]
I see that blog page has been created and blogs are in table. Can you give me more detail about this issue ?

![screencapture-localhost-4200-tr-blogs-2023-03-28-23_10_05](https://user-images.githubusercontent.com/48697010/228369316-8b279d79-a581-491c-af91-f3e4b14ca610.png)

**Comment by 7alip** [comment]
@ertugrul-aydin I'm sorry, I don't realized that the blog pages are already created. We forgot to close the issue. I close it now.
