### ISSUE TITLE
Add topic keyword filter

### ISSUE THREAD

**Issue by 7alip** [wsvvrijheid/monorepo#311]
Add filter buttons in `apps/admin/pages/news`. When you click a button, you can set the keyword to `searchItem` state. Filtering should be case insensitive. Buttons can be horizontally scrollable when the viewport gets smaller (overflowX: auto).

```ts
const keywords = {
  tr: ["insan haklari", "işkence"],
  en: ["human rights", "torture"],
  nl: ["mensenrechten", "marteling"]
}

<ButtonGroup>
  {keywords[locale].map(keyword => ...}
```

<img width="1370" alt="Screenshot 2023-01-02 at 16 28 34" src="https://user-images.githubusercontent.com/22167684/210251643-d392e033-3a9e-403c-8b34-c17045f4c2ae.png">

**Comment by 7alip** [comment]
@MustafaTRKYLMZ What else can we add to the keywords list?

**Comment by MustafaTRKYLMZ** [comment]
> @MustafaTRKYLMZ What else can we add to the keywords list?

we can add 
özgürlük, tutsak bebekler, cezaevi ihlalleri, geri itme ( push back), hasta tutuklular, tutuklu gazeteciler, yaṣam hakkı, kadın hakları, eğitim hakkı,

**Comment by 7alip** [comment]
> we can add özgürlük, tutsak bebekler, cezaevi ihlalleri, geri itme ( push back), hasta tutuklular, tutuklu gazeteciler, yaṣam hakkı, kadın hakları, eğitim hakkı,

We should probably create different list for each language.

Another important point is to improve filtering. For example, rather than `hasta tutuklular`, we can search for `hasta + tutuklu` to get more results. Maybe later, we can save news content without having to fetch it from the frontend. The aim of saving the content is to be able to do backend search/filtering for news content as well.

**Comment by MustafaTRKYLMZ** [comment]
> > we can add özgürlük, tutsak bebekler, cezaevi ihlalleri, geri itme ( push back), hasta tutuklular, tutuklu gazeteciler, yaṣam hakkı, kadın hakları, eğitim hakkı,
> 
> We should probably create different list for each language.
> 
> Another important point is to improve filtering. For example, rather than `hasta tutuklular`, we can search for `hasta + tutuklu` to get more results. Maybe later, we can save news content without having to fetch it from the frontend (otherwise we might fetch huge data). The aim of saving the content is to be able to do backend search/filtering for news content as well.

Can we make dinamic filter.? If we want we can create new filter world instand of static key world.
For example 'add new key world, update or delete'
