### ISSUE TITLE
Create custom like and view routes for Art and Blog

### ISSUE THREAD

**Issue by 7alip** [wsvvrijheid/monorepo#412]
Unauthenticated users can like and view arts and blogs. So far, we use `update` mutation to increase these values. Allowing update endpoint to public users is super insecure.

Tasks

- [x] Create Strapi routes `api/arts/like`, `api/arts/view`, `api/blogs/like`, `api/blogs/view` 
  - apps/api/src/api/art/routes/custom.ts
  - apps/api/src/api/blog/routes/custom.ts
- [x] Create Strapi controllers 
  - apps/api/src/api/art/controllers/custom.ts
  - apps/api/src/api/blog/controllers/custom.ts
 - [x] Adjust controllers for both authenticated and public user
   - **like**: If `ctx.state.user` exist add user id to `likers` or remove it from `likers`
   - If request is made by public user increase or decrease `likes` count
 - [x] Adjust `useViewArtMutation`, `useLikeArtMutation`, `useViewBlogMutation` and `useLikeBlogMutation`

**Comment by hasancomce** [comment]
All of these tasks have already been completed on the linked branch.
