### ISSUE TITLE
Wees Academy main page

### ISSUE THREAD

**Issue by MustafaTRKYLMZ** [wsvvrijheid/monorepo#502]
https://www.figma.com/file/eXv5LTPzTT9sPJHxy8MUr6/WSVV?node-id=2433-8879&t=DHHMjszDft2gtUl0-0

- [x] create course page in platforms/weesacademy
- [x]  add course cards
- [x] Courses card image url - "/uploads/courses_image_3c3a1382bd.png"
- [x] software card image url - "/uploads/software_card_f3408ac222.jpeg"
- [x] seminars card image url - "/uploads/Seminars_card_0a3a008777.jpeg"

**Comment by bllakcn** [comment]
- [ ] Wees Academy's description in Strapi should be updated according to the new concept.
- [ ] Academy has projects on its page. It needs images to display on the cards.

**Comment by 7alip** [comment]
@bllakcn Academy projects could be static for now. For the images, you can add any file to Strapi media library and use its remote link
