### ISSUE TITLE
Edit blog Save button doesn't work

### ISSUE THREAD

**Issue by MustafaTRKYLMZ** [wsvvrijheid/monorepo#724]
![image](https://github.com/wsvvrijheid/monorepo/assets/58182269/3e4ab045-4825-45bc-9b8d-fba168781e79)
In the blog edit page "save" button doesn't working.

**Comment by 7alip** [comment]
@MustafaTRKYLMZ We can log `useForm`'s formState.errors to see if it's because of validation.

**Comment by 7alip** [comment]
@MustafaTRKYLMZ Closing this since it works for me both locally and in production
