### ISSUE TITLE
Fix updating post stats on locale change

### ISSUE THREAD

**Issue by 7alip** [wsvvrijheid/monorepo#736]
<img width="1361" alt="Screenshot 2023-07-25 at 08 34 40" src="https://github.com/wsvvrijheid/monorepo/assets/22167684/a2f80a5c-ce2a-491a-88db-1ab1b0c3d7d2">

**Comment by MustafaTRKYLMZ** [comment]
> <img alt="Screenshot 2023-07-25 at 08 34 40" width="1361" src="https://user-images.githubusercontent.com/22167684/255811527-a2f80a5c-ce2a-491a-88db-1ab1b0c3d7d2.png">

I couldn't understand exactly what the problem was. Can you explain briefly? @7alip

**Comment by 7alip** [comment]
> I couldn't understand exactly what the problem was. Can you explain briefly? @7alip

When you change the language, it adds stats values to the previous values.

Assume there are 50 shares total in TR, 20 in NL, and 30 in EN. You go to TR first. Then you switch to the Netherlands. The total number of shares is 50 + 20. Then you change to EN. It becomes 50 + 20 + 30.
