### ISSUE TITLE
Bug in link in foundation activities page 

### ISSUE THREAD

**Issue by MustafaTRKYLMZ** [wsvvrijheid/monorepo#772]
https://www.wsvvrijheid.nl/activities/bir-muelteci-goezuenden-hollanda-temali-karma-sergi-wolvega-kuetuephanesi-nde-yapildi

it should be https://www.wsvvrijheid.nl/**tr/**activities/bir-muelteci-goezuenden-hollanda-temali-karma-sergi-wolvega-kuetuephanesi-nde-yapildi

language should be add
Seo should be fix

**Comment by 7alip** [comment]
Fixed in dev
