### ISSUE TITLE
Donations page filters

### ISSUE THREAD

**Issue by 7alip** [wsvvrijheid/monorepo#800]
**Todos**

- [x] Add `MonthPicker` to `apps/dashboard/pages/donations.tsx` from `@wsvvrijheid/ui`

```tsx
 <PageHeader
   onSearch={handleSearch}
   searchPlaceHolder={'Search by email'} // Update this
 >
     <MonthPicker onRangeSelect={handleSelect} />
 </PageHeader>
 ```
 
 - [x] Apply `createdAt` filters for donations (gte: startDate, lt: endDate)

**Comment by MustafaTRKYLMZ** [comment]
Actually, It is about improved table. It is not filter. For example in the table we can see month sum. But If you say filter is beter, we can try it.

**Comment by 7alip** [comment]
> 

It's in another issue #802
