### ISSUE TITLE
Add join team button to software page

### ISSUE THREAD

**Issue by MustafaTRKYLMZ** [wsvvrijheid/monorepo#893]
- [ ] Add join team button to software page

- [ ] Add link to button (https://www.wsvvrijheid.nl/tr/join) 
- [ ] Add submenu to Wees Academy (submenus Software, Cources and Seminars)

**Comment by 7alip** [comment]
@MustafaTRKYLMZ Adding submenu to the header is a big task and not specific for WeesAcademy. We can create a separate task for it if it's important

**Comment by MustafaTRKYLMZ** [comment]
Finding courses, semalinar and software can be easy. That is why I said it
