### ISSUE TITLE
Like art ids are stored as null

### ISSUE THREAD

**Issue by 7alip** [wsvvrijheid/monorepo#925]
<img width="493" alt="Screenshot 2023-10-23 at 15 19 15" src="https://github.com/wsvvrijheid/monorepo/assets/22167684/31708191-50ea-4194-83f4-75a0944c4e66">

**Comment by 7alip** [comment]
Why the id of the art is being saved as null?

**Comment by hasancomce** [comment]
This issue is completed, pull request is opened and merge is done.
